[package]
name = "ruscan"
version = "0.0.1"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Network
pnet = "0.34"
pnet_datalink = "0.34"
ipnetwork = "0.20"
dns-lookup = "2.0"

# Parsing & exports
csv = "1.2"
serde_yaml = "0.9"
rand = "0.8.5"
log = "0.4.20"
env_logger = "0.10.1"
window-shadows = "0.2.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
